### ISSUE TITLE
anyone else receiving gibberish from the feed? 

### ISSUE THREAD

**Issue by jonathanstrong** [agarwalyeshu/node-okex-ws-spot#1]
```console
$ cd example
$ node index.js 
undefined:1
M�;
^

SyntaxError: Unexpected token M in JSON at position 0
    at Object.parse (native)
    at WebSocket.socket.on.data (/home/jstrong/src/node-okex-ws-spot/index.js:57:38)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at Receiver._receiver.onmessage (/home/jstrong/src/node-okex-ws-spot/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/home/jstrong/src/node-okex-ws-spot/node_modules/ws/lib/Receiver.js:380:14)
    at Receiver.getData (/home/jstrong/src/node-okex-ws-spot/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/jstrong/src/node-okex-ws-spot/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/jstrong/src/node-okex-ws-spot/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/home/jstrong/src/node-okex-ws-spot/node_modules/ws/lib/WebSocket.js:138:22)
```

**Comment by jonathanstrong** [comment]
messages are now compressed with gzip/deflate
